### ISSUE TITLE
triggering UB without unsafe

### ISSUE THREAD

**Issue by JRazek** [tracel-ai/cubecl#42]
```rust
use cubecl::prelude::*;
use zerocopy::AsBytes;

#[cube(launch)]
fn add_kernel<F: Float>(lhs: &Array<F>, rhs: &Array<F>, output: &mut Array<F>) {
    let pos = ABSOLUTE_POS;

    //no bound check
    output[pos] = lhs[pos] + rhs[pos];
}

fn main() {
    let dev = cubecl::cuda::CudaDevice::default();
    let client = cubecl::cuda::CudaRuntime::client(&dev);

    let lhs_buff = client.create([0f32, 1f32, 2f32, 3f32].as_bytes());
    let rhs_buff = client.create([4f32, 5f32, 6f32, 7f32].as_bytes());

    let output = client.empty(4 * core::mem::size_of::<f32>());

    add_kernel::launch::<F32, cubecl::cuda::CudaRuntime>(
        &client.clone(),
        CubeCount::Static(1, 1, 1),
        CubeDim::new(16, 1, 1),//here
        ArrayArg::new(&lhs_buff, 4),
        ArrayArg::new(&rhs_buff, 4),
        ArrayArg::new(&output, 4),
    );

    let output_bytes = client.read(output.binding());
    let output = f32::from_bytes(&output_bytes);

    println!("{:?}", output);
}
```

This code triggers UB. 
Idk how you might ensure soundness within kernel, but IMO it should not be possible to do without `unsafe`. 

```
$ compute-sanitizer ./target/debug/cubecl_testing
========= COMPUTE-SANITIZER
========= Invalid __global__ read of size 4 bytes
=========     at kernel+0x150
=========     by thread (8,0,0) in block (0,0,0)
=========     Address 0x6e6000020 is out of bounds
=========     and is 1 bytes after the nearest allocation at 0x6e6000000 of size 32 bytes
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x2efadf]
...
```

**Comment by nathanielsimard** [comment]
@JRazek We are currently migrating every kernel in Burn to ensure they perform proper bounds checks. We can't automate this process easily because it would significantly impact performance (by up to 30% or more), which isn't viable in a high-performance computing scenario. It's generally better to use an early return in a kernel when the unit shouldn't perform any computation, but this approach doesn't work when you have sync_units in a cube. When the cube_dim and cube_count match, no bounds checks should be necessary.

Branching in GPU code is very expensive, so the best possible approach would be to trigger an error in debug mode using `#[cfg(test)]`. However, I'm not sure how we could implement error handling in GPU code either 😅.

We could adopt the same API as `wgpu`, where you can compile a module with `create_shader_module_unchecked`, which is an unsafe function. I'm gonna look into that.

**Comment by JRazek** [comment]
@nathanielsimard 
I get the limitations, but it still should not be possible to cause UB without explicit usage of unsafe.
