### ISSUE TITLE
Questions about project

### ISSUE THREAD

**Issue by giannissc** [tracel-ai/cubecl#55]
In particular, I am interested to know:
- Is the aim to be a single-source compute language like CUDA?
- Can you run the same kernels both in the CPU and GPU?
- Is the aim to expose a set of common capabilities, or do you intend to expose backend specific capabilities as well?
- How does the performance compare to [rust-gpu](https://github.com/EmbarkStudios/rust-gpu) and [krnl](https://github.com/charles-r-earp/krnl)?
- How does the feature set compare to rust-gpu and krnl?
- Could this be used to do [advanced compute](https://github.com/modularml/mojo/discussions/1147)?

**Comment by AdrianEddy** [comment]
A few more questions from me:
- Does/will it support interacting with gpu resources without going through the CPU, for example passing `CUdeviceptr` as input or output buffer or `wgpu::Buffer` or similar?
- Is OpenCL backend in scope?

**Comment by nathanielsimard** [comment]
1. Is the aim to be a single-source compute language like CUDA?
   Yes, you should be able to do everything in Rust, but you can also include other source (raw) kernels, like WGSL for the WGPU backend.

2. Can you run the same kernels both in the CPU and GPU?
   Not at the moment, but yes, in the future. We need to create a CPU runtime to do that; it's planned.

3. Is the aim to expose a set of common capabilities, or do you intend to expose backend specific capabilities as well?
   Both. We need to expose backend-specific capabilities if we want to leverage all hardware. We will do it similarly to how we support matrix-multiply and accumulate instructions.

4. How does the performance compare to [rust-gpu](https://github.com/EmbarkStudios/rust-gpu) and [krnl](https://github.com/charles-r-earp/krnl)?
   No comparison benchmarks against them yet, but CubeCL is really optimized for speed, so it should be faster or the same as writing plain CUDA code, mostly because of vectorization, our memory management strategy, and our variable pool that optimizes the number of registers needed for a kernel.

5. How does the feature set compare to rust-gpu and krnl?
   Hard to say, but Comptime and automatic dynamic vectorization are pretty unique.

6. Could this be used to do https://github.com/modularml/mojo/discussions/1147?
   The more we support Rust features, the easier it is going to become.

7. Does/will it support interacting with gpu resources without going through the CPU, for example passing CUdeviceptr as input or output buffer or wgpu::Buffer or similar?
   I don't think it's easy or possible to do right now, but it's not out of scope.

8. Is OpenCL backend in scope?
   No, OpenCL is pretty much dead. Vulkan Compute is kind of the replacement.
